AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: '"Dicom Lambda Validation \n"

  '
Parameters:
  gitHubBranch:
    Type: String
    Default: master
Globals:
  Function:
    AutoPublishAlias: live
    Handler: index.handler
    MemorySize: 256
    Runtime: python3.7
    Timeout: 300
    Tracing: Active
Resources:
  PyDicomLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: PyDicom
      ContentUri: s3://covid-bucket-app185805-dev/4d3cb456b7a00bae40e6f9eafd7f709f
      CompatibleRuntimes:
      - python3.8
      - python3.7
      RetentionPolicy: Delete
  Validation:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://covid-bucket-app185805-dev/a142483062fe8b9607002c9b40974883
      Layers:
      - Ref: PyDicomLayer
      Policies:
      - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      - SQSSendMessagePolicy:
          QueueName:
            Fn::Sub: '{{resolve:ssm:/covid19l3/${gitHubBranch}/sqsname:1}}'
      - S3CrudPolicy:
          BucketName:
            Fn::Sub: '{{resolve:ssm:/covid19l3/${gitHubBranch}/s3Bucket:1}}'
      VpcConfig:
        SecurityGroupIds:
        - '{{resolve:ssm:/covid19l3/securitygroup:1}}'
        SubnetIds:
        - '{{resolve:ssm:/covid19l3/lambdasubnet1:1}}'
        - '{{resolve:ssm:/covid19l3/lambdasubnet2:1}}'
      FileSystemConfigs:
      - Arn:
          Fn::Sub: '{{resolve:ssm:/covid19l3/${gitHubBranch}/efslambdaarn:1}}'
        LocalMountPath: /mnt/tmp
      Environment:
        Variables:
          Bucket:
            Fn::Sub: '{{resolve:ssm:/covid19l3/${gitHubBranch}/s3Bucket:1}}'
          queueUrl:
            Fn::Join:
            - ''
            - - https://sqs.
              - Fn::Sub: ${AWS::Region}
              - .amazonaws.com/
              - Fn::Sub: ${AWS::AccountId}
              - /
              - Fn::Sub: '{{resolve:ssm:/covid19l3/${gitHubBranch}/sqsname:1}}'
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
        - Validation
        - Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount:
        Ref: AWS::AccountId
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:s3:::'
          - Fn::Sub: '{{resolve:ssm:/covid19l3/${gitHubBranch}/s3Bucket:1}}'
  lambdaParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub: /covid19l3/${gitHubBranch}/lambdaArn
      Type: String
      Value:
        Fn::GetAtt:
        - Validation
        - Arn
      Description:
        Fn::Sub: LambdaArn for covid19l3 ${gitHubBranch}
Outputs:
  ValidationArn:
    Value:
      Fn::GetAtt:
      - Validation
      - Arn
