AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    "Dicom Lambda Validation \n"

Parameters:
  gitHubBranch:
    Type: String
    Default: master

Globals:
  Function:
    AutoPublishAlias: live
    Handler: index.handler
    MemorySize: 512
    Runtime: python3.7
    Timeout: 60
    Tracing: Active

Resources:
  PyDicomLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        Description: PyDicom
        ContentUri: ../layers/pydicom.zip
        CompatibleRuntimes:
          - python3.8
          - python3.7
        RetentionPolicy: Delete

  Validation:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./validation/
      Layers:
      - !Ref PyDicomLayer
      Policies:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - SQSSendMessagePolicy:
            QueueName: 
              !Sub '{{resolve:ssm:/covid19l3/${gitHubBranch}/sqsname:1}}'
        - S3CrudPolicy:
            BucketName:
              !Sub '{{resolve:ssm:/covid19l3/${gitHubBranch}/s3Bucket:1}}'
      VpcConfig: 
        SecurityGroupIds:
          - '{{resolve:ssm:/covid19l3/securitygroup:1}}'
        SubnetIds:
          - '{{resolve:ssm:/covid19l3/lambdasubnet1:1}}'
          - '{{resolve:ssm:/covid19l3/lambdasubnet2:1}}'
      FileSystemConfigs:
        - Arn: !Sub '{{resolve:ssm:/covid19l3/${gitHubBranch}/efslambdaarn:1}}' 
          LocalMountPath: /mnt/tmp
      Environment:
        Variables:
          Bucket:
            !Sub '{{resolve:ssm:/covid19l3/${gitHubBranch}/s3Bucket:1}}'
          queueUrl: 
              !Join
                - ''
                - - 'https://sqs.'
                  - !Sub '${AWS::Region}'
                  - '.amazonaws.com/'
                  - !Sub '${AWS::AccountId}'
                  - '/'
                  - !Sub '{{resolve:ssm:/covid19l3/${gitHubBranch}/sqsname:1}}'

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: 
        !GetAtt Validation.Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: 
         !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Sub '{{resolve:ssm:/covid19l3/${gitHubBranch}/s3Bucket:1}}'

  lambdaParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        !Sub /covid19l3/${gitHubBranch}/lambdaArn
      Type: String
      Value: 
        !GetAtt Validation.Arn
      Description: !Sub LambdaArn for covid19l3 ${gitHubBranch}

Outputs:
  ValidationArn:
      Value: !GetAtt Validation.Arn